# Generated by Django 4.2 on 2024-11-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_post_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('nep_timestamp', models.DateTimeField(blank=True, null=True)),
                ('en_timestamp', models.DateTimeField(blank=True, null=True)),
                ('original_title', models.CharField(max_length=255)),
                ('translated_title', models.CharField(max_length=255)),
                ('original_content', models.TextField()),
                ('translated_content', models.TextField()),
                ('image_source', models.URLField(blank=True, null=True)),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
