# Generated by Django 4.2 on 2024-11-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_newsarticle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='nep_timestamp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
