# Generated by Django 4.2 on 2024-11-09 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_newsarticle_en_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='newsArticleLikes_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='view',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='NewsArticleComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('comment', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('news_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.newsarticle')),
            ],
            options={
                'verbose_name_plural': 'NewsArticleComment',
            },
        ),
        migrations.CreateModel(
            name='NewsArticleBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('news_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.newsarticle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'NewsArticleBookmark',
            },
        ),
    ]
