# Generated by Django 4.2 on 2024-11-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_newsarticle_likes_newsarticle_view_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='sentiment_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
