# Generated by Django 4.2 on 2024-11-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_newsarticle_sentiment_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='en_timestamp',
            field=models.DateTimeField(blank=True, max_length=50, null=True),
        ),
    ]
