# Generated by Django 4.2 on 2024-11-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_newsarticle_en_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.IntegerField()),
                ('time_period', models.DateField()),
                ('sentiment_average', models.FloatField()),
                ('articles_count', models.IntegerField()),
            ],
        ),
    ]
