# Generated by Django 4.2 on 2024-11-23 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_topictrend'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordSentimentTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('time_period', models.DateField()),
                ('sentiment_average', models.FloatField()),
                ('articles_count', models.IntegerField()),
            ],
            options={
                'unique_together': {('word', 'time_period')},
            },
        ),
        migrations.DeleteModel(
            name='TopicTrend',
        ),
    ]
