# Generated by Django 4.2 on 2024-12-14 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_wordsentimenttrend_delete_topictrend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wordsentimenttrend',
            old_name='time_period',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='wordsentimenttrend',
            old_name='sentiment_average',
            new_name='sentiment_score',
        ),
        migrations.AlterUniqueTogether(
            name='wordsentimenttrend',
            unique_together={('word', 'date')},
        ),
        migrations.AddField(
            model_name='wordsentimenttrend',
            name='news_article',
            field=models.ForeignKey(default=4123, on_delete=django.db.models.deletion.CASCADE, to='api.newsarticle'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='wordsentimenttrend',
            name='articles_count',
        ),
    ]
