# Generated by Django 4.2 on 2024-12-14 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_time_period_wordsentimenttrend_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wordsentimenttrend',
            options={'verbose_name_plural': 'WordSentimentTrend'},
        ),
        migrations.AlterUniqueTogether(
            name='wordsentimenttrend',
            unique_together=set(),
        ),
    ]
